import type { Metadata } from "next";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function({children}: {children: React.ReactNode}){
  return (
    <div>
      <div className="p-4 text-center border-b">
          20% Off on signin
      </div>
      {children}
    </div>
  )
}
