import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar, Prop} from "@/components/navbar";

const props: Prop[] = [
  {
    buttonContent: 'Home',
    link: '/',
  },
  {
    buttonContent: 'Server Page',
    link: '/static-page',
  },
  {
    buttonContent: 'Client Page',
    link: '/interactive-page',
  },
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar props={props}/>
        {children}
        </body>
    </html>
  );
}